services:
  postgres:
    image: postgres:14.9
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data14:/var/lib/postgresql/data
    networks:
      - backend

networks:
    backend:
        driver: bridge
